---
- name: install fuluentd
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: install plugin
      gem:
        executable: /usr/sbin/td-agent-gem
        name: fluent-plugin-elasticsearch
        state: present
        user_install: no
